### ISSUE TITLE
API에 정보 추가

### ISSUE THREAD

**Issue by kreit-eunjun** [dosaeng/move-in-server#5]
- [x] GET /agent-api/filter-card

아래 정보가 추가 되어야 함
- 해당 필터에 대해 내가 제안 요청을 보냈는가?
- 해당 필터에 대해 보낸 제안에 대해 사용자가 상담 요청을 했는가?

![image](https://github.com/dosaeng/move-in-server/assets/152147889/06c6fed9-2d14-4275-a3ac-b669e285067c)

---

- [x] GET /app-user-api/filter-card

아래 정보가 추가 되어야 함
- status
- recommendation_due_date

---

- [ ] POST /app-user-api/filter-card

요청 본문에서 아래 정보 제거
- status
- recommendation_due_date

--- 
- [x] PATCH /app-user-api/filter-card/{filterCardId}/open

해당 API 요청 시 filter의 recommendation_due_date 설정 되어야 함 
- `현재 + 7일`로 설정

**Comment by HANJIN-O** [comment]
@kreit-eunjun 
## POST /app-user-api/filter-card
required값이 아니라 안넣어줘도 동작합니다.
DTO를 조회용 생성용 같이써서 그렇습니다.

**Comment by kreit-eunjun** [comment]
아 넵 필수값 아니면 수정 안해도 될 것 같습니다.
